### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by JoanneYuan** [Latias94/latias94.github.io#1]
很喜欢你的blog的风格。可以请问你首页的图片是从哪里下载的嘛。以及blog用的是什么模板呀。
谢谢了

**Comment by Latias94** [comment]
你好，马里奥是 Chill Mario 的作品，链接在 [Chill Mario](https://www.behance.net/gallery/87602523/Chill-Mario)。  
博客模板用的是 [jerryc127/hexo-theme-butterfly](https://github.com/jerryc127/hexo-theme-butterfly)。
